apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  #ports to be mappped up on target objects
  ports:
    #port exposed to outside world
    - port: 3050
      #any incoming traffic forwared to port 3000
      targetPort: 3000
      #node port is accessed by browser
      nodePort: 31515
  #any other object running with label component: web the file act up on it..linked by sselctor in sservice and  in kind pod by labels
  selector:
    component: web